title: Blog do Igor Venturelli
author: Igor Venturelli
email: igventurelli@gmail.com
description: >-
  Programação, Segurança e Tecnologia em geral
baseurl: ""
url: "https://igventurelli.me" 
github_username:  igventurelli
google_analytics: UA-159165520-1
disqus:
  shortname: igventurelli
theme: minima
plugins:
  - jekyll-feed